cmdline:
  app-name: CmdLineArgs
  file:
    path-to-resources: /cmd-line/
    path-to-help-files: /help-files/ # src/main/resources/cmd-line/help-files
    definition-file: cmdline-definition.jca
    default-input-file: default-input-file.txt
    default-output-file: default-output-file.txt
  properties:
    global:
      option:
        prefix:
          name:
            long: "--"
            short: "-"
  regex:
    option:
      name: # OR ^(--([a-zA-Z]+[^0-9\\W]))(=(\\w+))?$
        long: ^(--([a-zA-Z]+[^0-9\W]))(=((\w+)(\.([a-zA-Z0-9]+))?))?$
        short: ^(--([a-zA-Z]+[^0-9\W]))(=((\w+)(\.([a-zA-Z0-9]+))?))?$
    parameter: # OR ^([a-zA-Z0-9]+)(\\.([a-zA-Z0-9]+))?$
      file: ^(\w+)(\.([a-zA-Z0-9]+))?$
      anything: ^(\w+)?$
  log:
    paragraph:
      crlf: \r\n
      tab: \t
    error:
      prefix: "ERROR: "
    section:
      delimiter:
        minus: "------------------------------------------------------------------"
        equal: "=================================================================="
  service:
    display-service:
      message-with-param:
        file-exist:
          file-exist: 'The file/folder "{}" exists.'
          file-not-exist: 'The file/folder "{}" does not exist'
          is-folder: '"{}" is a directory. Need a file.'
          is-file: '"{}" is a file.'
        write-to-file:
          successful: Successful write to file.
          failed: Failed to write to file.
        read-from-file:
          successful: Successful read from file.
          failed: Failed to read from file.
